create table if not exists public.treatment_registry (
  id text primary key,
  label text not null,
  aliases jsonb not null default '[]'::jsonb,
  category text not null,
  estimated_minutes integer not null default 5 check (estimated_minutes > 0),
  status text not null default 'Draft' check (status in ('Draft','Approved')),
  version text not null default '0.1',
  modules jsonb not null default '[]'::jsonb,
  content jsonb not null default '[]'::jsonb,
  consent_points jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.treatment_registry_history (
  id bigint generated by default as identity primary key,
  treatment_id text not null,
  version text not null,
  snapshot jsonb not null,
  changed_by text,
  changed_at timestamptz not null default now()
);

create index if not exists treatment_registry_status_idx on public.treatment_registry(status);
create index if not exists treatment_registry_history_treatment_idx on public.treatment_registry_history(treatment_id, changed_at desc);

alter table public.treatment_registry enable row level security;
alter table public.treatment_registry_history enable row level security;

-- Browser clients do not get direct write access. Sitora's server-side API uses the service role.
-- Add organisation/auth-specific read policies later when authenticated production roles are introduced.

comment on table public.treatment_registry is 'Governed Sitora treatment definitions used by Before, During and After engines.';
comment on table public.treatment_registry_history is 'Immutable snapshots of superseded treatment registry versions.';
